---
abstract: 'POSIX functions with wide-char strings.'
author:
  - 'Kevin Ryde <user42_kevin@yahoo.com.au>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: POSIX-Wide
no_index:
  directory:
    - t
    - inc
    - devel
    - xt
requires:
  Encode: '2.25'
  Encode::Locale: '0'
  perl: '5.008001'
resources:
  homepage: http://user42.tuxfamily.org/posix-wide/index.html
  license: http://www.gnu.org/licenses/gpl.html
version: '9'
